version: "3.9"
services:
  postgre:
    image: postgres:13.3
    environment:
      POSTGRES_DB: items
      POSTGRES_USER: itempguser
      POSTGRES_PASSWORD: itempguser
    ports:
      - "5432:5432"

  sls-mettle:
    depends_on:
      - postgre
    ports:
      - "8080:8080"
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgre:5432/items
