version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: items
      POSTGRES_USER: itempguser
      POSTGRES_PASSWORD: itempguser
    ports:
      - "5432:5432"